### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by Aniket-Engg** [EthereumRemix/sol-test#4]
- [ ] Running `ls` command doesn't seem required https://github.com/EthereumRemix/sol-test/blob/main/src/index.ts#L11
- [ ] `npm init` is not required to install a module globally  https://github.com/EthereumRemix/sol-test/blob/main/src/index.ts#L24 
- [ ] Support other options along with `compiler-version` . All options are:
```
 -c, --compiler <string>  set compiler version (e.g: 0.6.1, 0.7.1 etc)
  -e, --evm <string>       set EVM version (e.g: petersburg, istanbul etc)
  -o, --optimize <bool>    enable/disable optimization
  -r, --runs <number>      set runs (e.g: 150, 250 etc)
```

- [ ]  Update readme to explain the options and their usage in job configuration
- [ ] Just to add, it seems working fine without this step:
```
name: Environment Setup
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
```
If that is not required, readme can be updated.
